<?php
/**
 * Created by PhpStorm.
 * User: QuangPT
 * Date: 4/11/2019
 * Time: 3:00 AM
 */
namespace App\Services;

use App\Event;
use App\User;


class EventService extends BaseService {

    /**
     * CommentService constructor.
     */
    public function __construct() {
        parent::__construct();
    }

    /**
     * @return string
     */
    public function getModel()
    {
        return Event::class; // TODO: Change the autogenerated stub
    }

    /**
     * Create a Event
     * @param array $attribute
     * @return bool
     */
    public function createEvent($attribute = []) {
        if ($this->create($attribute)) {
            return true;
        }
        return false;
    }

    public function searchEvent($dateStart, $dateEnd) {
        $result = array();
        $events = Event::orderBy("created_at")->get();
        $dateStart = $dateStart;
        $dateEnd = $dateEnd;
        for ($i = 0; $i < sizeof($events); $i++) {
            $dateEvent = $events[$i]->event_date;
            if (($dateEvent >= $dateStart) && ($dateEvent <= $dateEnd)) {
                array_push($result, $events[$i]);
            }
        }
        return $result;
    }

}